server:
  port: 10000

spring:
  application:
    name: rical-backend-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.0.4:8848
  datasource:
    url: jdbc:mysql://172.18.0.3:3306/user_center
    hikari:
      username: root
      password: meisql
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - dversion
      - swagger
      - job

