job:
  admin:
    accessToken: accessToken
    address:
    ip:
    adminAddresses: http://172.21.0.14:9001
    port: 9999
    logPath: /home/app/applogs/job-center/jobhandler
    logRetentionDays: 30
