server:
  port: 10000

spring:
  application:
    name: rical-backend-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.21.0.14:8848
  datasource:
    url: jdbc:mysql://172.21.0.14:3306/user_center
    hikari:
      username: root
      password: meisql
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - dversion
      - swagger

