server:
  port: 8000

spring:
  application:
    name: rical-backend-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848
  profiles:
    include:
      - dubbo
      - consumer