dubbo:
  application:
    # 应用名称
    name: sprica-dubbo-consumer
    id: sprica-dubbo-consumer
  registry:
    # 注册中心地址
    address: nacos://103.45.105.132:8848/
  protocol:
    # 传输协议
    name: dubbo
    # ip不可为127.0.0.1 -> 本机ip
    host: 192.168.3.206
    # 随机端口
    port: 20880
