xxl:
  job:
    admin:
      accessToken: accessToken
      address:
      ip:
      adminAddresses: http://localhost:8001/job-center-admin
      port: 9999
      logPath: /home/app/applogs/job-center/jobhandler
      logRetentionDays: 30