server:
  port: 8101

spring:
  application:
    name: rical-backend-provider
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848
  profiles:
    include:
      - dubbo
      - provider
      - consumer
      - job

