server:
  port: 8101

spring:
  application:
    name: rical-backend-provider
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848
  datasource:
    url: jdbc:mysql://103.45.105.132:3306/user_center
    hikari:
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - job

# Swagger
swagger:
  title: Rical-Backend
  description: Rical-Backend后端服务文档，方便前端调用
  author: wtrue
  self-url: www.meidanlong.com
  email: meidanlong@qq.com
  version: 1.0.0-SNAPSHOT
  web: www.sprica.cn