
xxl:
  job:
    accessToken: accessToken
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address:
      appname: wtrue-job-center
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999